fix: Fixing path to git hooks

diff --git a/scripts/pre-push b/scripts/pre-push
--- a/scripts/pre-push
+++ b/scripts/pre-push
@@ -4,18 +4,25 @@ ISSUES="no"
 
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
+
 for FILE in `git diff-index --name-only master`; do
   # do not check files others than *.py
-  if [[ $FILE == *.py ]]; then
-    if ! flake8 --config $SCRIPT_DIR/../.flake8 $FILE; then
+  if [[ "$SCRIPT_DIR/../$FILE" == *.py ]]; then
+    if ! flake8 --config $SCRIPT_DIR/../.flake8 "$SCRIPT_DIR/../$FILE"; then
         ISSUES="yes"
     fi
   fi
 done;
 
 if [[ $ISSUES == "no" ]]; then
+    GREEN=$'\e[0;32m';
+    NC=$'\e[0m';
+    echo "${RED}No linting errors detected. Push successfull${NC}";
+    exit 1
     exit 0
 else
-    echo "Please resolve linting issues";
+    RED=$'\e[0;31m';
+    NC=$'\e[0m'
+    echo "${RED}Push cancelled. Please resolve linting issues or use the --no-verify option${NC}";
     exit 1
 fi
