fix: Checking against Top Level

diff --git a/scripts/pre-push b/scripts/pre-push
--- a/scripts/pre-push
+++ b/scripts/pre-push
@@ -1,28 +1,24 @@
 #!/bin/bash
 
+echo $GIT_DIR
+
 ISSUES="no"
 
-SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-
-SCRIPT_RELATIVE=".."
-if [[ $(dirname $0) == ".git/hooks" ]]; then
-  SCRIPT_RELATIVE="../.."
-fi
+TOP_LEVEL=$(git rev-parse --show-toplevel)
 
 for FILE in `git diff-index --name-only master`; do
   # do not check files others than *.py
-  if [[ "$SCRIPT_DIR/../$FILE" == *.py ]]; then
-    if ! flake8 --config $SCRIPT_DIR/../.flake8 "$SCRIPT_DIR/../$FILE"; then
+  if [[ "$TOP_LEVEL/$FILE" == *.py ]]; then
+    if ! flake8 --config "$TOP_LEVEL/.flake8" ""$TOP_LEVEL/$FILE""; then
         ISSUES="yes"
     fi
   fi
-done;
+done
 
 if [[ $ISSUES == "no" ]]; then
     GREEN=$'\e[0;32m';
     NC=$'\e[0m';
-    echo "${RED}No linting errors detected. Push successfull${NC}";
-    exit 1
+    echo "${GREEN}No linting errors detected. Push successfull${NC}";
     exit 0
 else
     RED=$'\e[0;31m';
